### ISSUE TITLE
Downside of loading struct with view information

### ISSUE THREAD

**Issue by alilee** [schell/mogwai#60]
Hey @schell ,

Sorry I'm so long getting this feedback to you, but I was uneasy that your proposed solution for nesting had the reference to the view in the ```Component``` class. 

Would it be possible for the solution to leave the ```impl Component``` "clean" in that it has only problem-domain fields. This would mean that ```Gizmo``` etc. data structures would need to take up the burden, but has the massive benefit that the domain model is untouched except for ```impl Component```.   

Cheers,
Alister.

**Comment by schell** [comment]
No problem, @alilee! 

I think that would be an ideal situation but I don't know what the API would look like, nor how it could be accomplished. 

One way to look at it is that the type implementing `Component` is itself a user interface component, a gizmo, aka a widget. That component may have some internal state and some of that state may be other components. In some ways `mogwai` is an MVC library. It kinda has models because structs that implement `Component` look like they could be a pure data model. It has views. It has controllers in the form of `Gizmo`s. But none of the goals of the library are about purity or the separation of business and view logic. It's about describing a user interface and making it snappy.

If you have any ideas on how to approach the problem I will listen and would love to collaborate.

**Comment by schell** [comment]
Is this the nesting solution you're referring to? 

https://github.com/schell/mogwai/blob/master/cookbook/src/nest_component.md

**Comment by alilee** [comment]
Yes, that is what I was referring to. I get your point about goals.

Isn't Gizmo is itself a persistent parallel data structure relating Components to each other through txrx? A bigger gizmo would have ownership of the sub-components and methods to add/remove.

I easily lose my thread in the build-time/run-time transitions, so quite possibly am missing a critical step.

**Comment by schell** [comment]
> Isn't Gizmo is itself a persistent parallel data structure relating Components to each other through txrx?

I think so. It is definitely persistent. It could be parallel depending on the meaning - though in execution it is synchronous under the hood (because the JS runtime is single threaded). 

`Gizmo` most certainly relates components to each other through txrx. It only holds three things: a state var, a transmitter and a receiver. But a `Gizmo` is also the thing that makes implementors of `Component` *operable*. [`Gizmo::from_parts`](https://github.com/schell/mogwai/blob/976f64d517485057ceb1deb9e4f9afdeca512dae/mogwai/src/gizmo.rs#L30-L57) sets up the state var, binds any sub-components and wires updates into the view's rx.  

> A bigger gizmo would have ownership of the sub-components and methods to add/remove.

Yes, most likely. What I've found is that typically a `GIzmo` will retain another gizmo when it needs to couple to it in order to query or change its state. If there is no communication needed then you can simply construct a `ViewBuilder` in RSX from an implementor of `Component`:

```rust 
<div id="main">{ ViewBuilder::from(MySubcomponent::default()) }</div>
```

Ultimately there are other ways to keep from having to retain the sub-gizmo in a field - you could instead hold on to only the parts you need, eg the state var or the transmitter. Whether or not you _can_ do that depends on how the parent component plans to communicate with the child component - ie does it need to bind to it once at the parent's creation? Does the child often get replaced? Can you wait until later to create the sub-component? If so then we can defer creating the subcomponent until the update function receives a certain message. Then we can create a gizmo, bind its messages to the parent component and/or visa versa and, send its view to be added to the parent component's view (via a message) and then drop the sub-gizmo now that it's no longer needed. 

Something I haven't written about yet is the `patch:children` RSX attribute and the accompanying type `Patch<T>`. Together they describe run-time manipulation of a DOM node's children. This is very important here and I should expand the nested component  article with some more examples of that. Here's a quick example:

```rust
    fn update(&mut self, msg: &In, tx_view: &Transmitter<Out>, sub: &Subscriber<In>) {
        match msg {
            Something => { 
                tx_view.send(&Out::UpdateChildren(Patch::PushBack {
                    value: View::from(Gizmo::from(ChildComponent::default()).view_builder())
                }));
            }
        }
    }

    fn view(&self, tx: &Transmitter<In>, rx: &Receiver<Out>) -> ViewBuilder<HtmlElement> {
        builder! {
            <div id="the_parent" patch:children=rx.branch_map(|Out::UpdateChildren(patch)| patch.clone() >
            </div>
        }
    }
```

> I easily lose my thread in the build-time/run-time transitions, so quite possibly am missing a critical step.

This is worth investigating - is there something I should write in the README, introduction or cookbook that would demystify the concepts? Maybe I should state concretely what represents build-time setup and what represents run-time updates?

**Comment by schell** [comment]
Ultimately I'm still discovering what works best and at this point `mogwai` aims to give you a number of options instead of being opinionated about what the "one true way" is. Thanks for hanging in for the ride ;)

**Comment by schell** [comment]
@alilee feel free to join the channel and chat there as well https://app.element.io/#/room/#mogwai:matrix.org
