### ISSUE TITLE
Getting a type mismatch error when using mpsc::Sender as Sink

### ISSUE THREAD

**Issue by Dragonink** [schell/mogwai#93]
I tried doing a button which changes its classes when clicked on:
```rust
fn view() -> ViewBuilder<Dom> {
    const FOLDED_CLASS: &str = "folded";
    let (fold_tx, _fold_rx) = mpsc::channel::<()>(1);
    builder! {
        <button class=format!("{name} {folded}", name = firstname, folded = FOLDED_CLASS)
            on:click=fold_tx.contra_map(|ev: DomEvent| {
                ev.browser_event().unwrap().target().unwrap().dyn_ref::<HtmlElement>().unwrap().class_list().toggle(FOLDED_CLASS).unwrap();
            })>
        </button>
    }
}
```
and I got the error:
> **type mismatch resolving `<ContraMap<mogwai::channel::mpsc::Sender<()>, mogwai::event::DomEvent, ()> as mogwai::futures::Sink<mogwai::event::DomEvent>>::Error == SinkError`**
> expected struct `mogwai::channel::mpsc::SendError`, found enum `SinkError`

But when I tried using the broadcast types instead, the code compiles without error.

Am I misusing the mpsc channel ?

##### Versions
- Rust v1.57.0
- mogwai v0.52

**Comment by schell** [comment]
Before I get further into it - where does `firstname` come from?

**Comment by schell** [comment]
It's definitely odd that `broadcast::Sender` works for you as `Sink`, because it doesn't have a `Sink` implementation, which is a constraint of `Contravariant`. But this exposes an oversight of mine in 0.5.2 - I hadn't written an `IntoSenderSink` impl for `mpsc` channels. Luckily it's a moot point after `0.6.0` comes out, as that contains a major channel rework.

For now you should be fine using the broadcast channel like this: 
 ```rust
         fn view() -> ViewBuilder<Dom> {
            const firstname: &str = "dragonink";
            const FOLDED_CLASS: &str = "folded";
            let (fold_tx, _fold_rx) = broadcast::bounded::<()>(1);
            builder! {
                <button class=format!("{name} {folded}", name = firstname, folded = FOLDED_CLASS)
                 on:click=fold_tx.sink().contra_map(|ev: DomEvent| {
                     ev.browser_event()
                         .unwrap()
                         .target()
                         .unwrap()
                         .dyn_ref::<web_sys::HtmlElement>()
                         .unwrap()
                         .class_list()
                         .toggle(FOLDED_CLASS)
                         .unwrap();
                 })>
                </button>
            }
        }
```

Notice the extra `sink()` here. This is because mogwai simply re-exports `async_broadcast`, and `async_broadcast::Sender` is not `Sink`. 

In `0.6.0` this has all changed and mogwai provides wrappers for channels so all senders are `Sink` and all `Receivers` are `Stream`.

**Comment by schell** [comment]
I've added the necessary machinery to use `mpsc::Sender::sink` to match `broadcast` to 0.5.3. Let me know if that fixes your issue well enough.

**Comment by Dragonink** [comment]
> It's definitely odd that `broadcast::Sender` works for you as `Sink`, because it doesn't have a `Sink` implementation, which is a constraint of `Contravariant`.

It seems I did not explain it well, but of course I used the `broadcast::Sender::sink` method before the `.contra_map`.
My question was focused on why my code did not compile when using an mpsc channel.

> I've added the necessary machinery to use `mpsc::Sender::sink` to match broadcast to 0.5.3. Let me know if that fixes your issue well enough.

I will report the result as soon as I test the 0.5.3.
Thanks for your quick anwser !

**Comment by Dragonink** [comment]
> I've added the necessary machinery to use `mpsc::Sender::sink` to match `broadcast` to 0.5.3. Let me know if that fixes your issue well enough.

I tested the following code in 0.5.3 and it compiles:
```rust
fn view() -> ViewBuilder<Dom> {
    const FOLDED_CLASS: &str = "folded";
    let (fold_tx, _fold_rx) = mpsc::channel::<()>(1);
    builder! {
        <button class=format!("{name} {folded}", name = firstname, folded = FOLDED_CLASS)
            on:click=fold_tx.sink().contra_map(|ev: DomEvent| {
                ev.browser_event().unwrap().target().unwrap().dyn_ref::<HtmlElement>().unwrap().class_list().toggle(FOLDED_CLASS).unwrap();
            })>
        </button>
    }
}
```

But I stumbled upon another issue: the event seems not to be dispatched.
When using a broadcast channel, the event is dispatched on some buttons, but not on others.
And for both channels, the event is unbound from the button after I click on it.

Is it because I don't use `_fold_rx` ?

**Comment by schell** [comment]
Yes, if you don't **move** `_fold_rx` then the channel is closed because the receiver gets dropped. The the loop that sends event messages to `fold_tx` sees that it's closed and since it can't send messages it exits and the underlying event listener is removed. I can see you are currently using the stream like a callback (which is fine, because you only care about toggling this one class), but setting up just a bit more structure fixes your problem and gives you some headroom if you'd like to expand the capabilities of your widget (I'm including the entire test that I've put in the repo): 
```rust
    #[test]
    fn issue_93_dragonink_view() {
        use mogwai::prelude::*;
        use wasm_bindgen::JsCast;

        struct MyButton {
            firstname: String,
            folded_class: String,

            click_event: Output<DomEvent>,
        }

        impl MyButton {
            fn view(&self) -> ViewBuilder<Dom> {
                builder! {
                    <button class=format!("{name} {folded}", name = &self.firstname, folded = self.folded_class)
                    on:click=self.click_event.sink()>
                        </button>
                }
            }

            fn logic(self) -> Pin<Box<dyn Spawnable>> {
                Box::pin(async move {
                    while let Some(event) = self.click_event.get().await {
                        event
                            .browser_event()
                            .unwrap()
                            .target()
                            .unwrap()
                            .dyn_ref::<web_sys::HtmlElement>()
                            .unwrap()
                            .class_list()
                            .toggle(&self.folded_class)
                            .unwrap();
                    }
                })
            }
        }

        let my_btn = MyButton {
            firstname: "dragonink".to_string(),
            folded_class: "folded".to_string(),
            click_event: Output::default(),
        };

        let view = Component::from(my_btn.view())
            .with_logic(my_btn.logic())
            .build()
            .unwrap();
        view.run().unwrap();

    }
```
This brings up an interesting though though - how often do folks need to simply toggle one class on or off? I guess it must be pretty often if there's a JS API for it. Maybe `mogwai-html-macro` should have a special attribute for doing this? Something like: 

```rust
let (tx_active, rx_active) = broadcast::bounded::<bool>(1);
builder! {
    <button class:active=(true, rx_active) ></button>
}
...
```

The downside would be that domain-specific views would have to deal with this extra value+stream pair, even if the domain has no concept of "classes".

**Comment by schell** [comment]
What might be a bit more specific and ergonomic could be to write a function/macro helper that takes multiple boolean streams in a hashmap and constructs a class set from them, updating it each time any of them change. That wouldn't touch the underlying `ViewBuilder` machinery.

Just riffing over here 😅 .

**Comment by Dragonink** [comment]
Okay, I managed to make it working.
Thanks again for your help !

PS: a special `class` attribute would definitely be interesting.
